base_url = "http://api.yocard.staging.digicode.ua/mobileclient.svc/"

card_by_tag = base_url + "cardbytag"
change_device_identifier = base_url + "changedeviceidentifier"
change_device_registration = base_url + "changedeviceregistration"
change_subscribe_status = base_url + "changesubscribestatus"
checkin = base_url + "checkin"
confirm_identifier = base_url + "confirmidentifier"
create_card = base_url + "createcard"
create_card_by_offer = base_url + "createcardbyoffer"
create_fora_card = base_url + "createforacard"
create_foxtrot_card = base_url + "createfoxtrotcard"
delete_card = base_url + "deletecard"
# change_device_registration = base_url +
# change_device_registration = base_url +
# change_device_registration = base_url +
# change_device_registration = base_url +
# change_device_registration = base_url +
cards_url = base_url + "getcards"
categories_url = base_url + "getcategories"
blacklist_url = base_url + "getblacklist"
appversions_url = base_url + "getappversions"
foxtrotcard_url = base_url + "createfoxtrotcard"
offers_url = base_url + "getoffers"
retailers_url = base_url + "getretailers"